DevOps-01
JonathanBanerjee/wordle pull request #1
Opened 2022-12-12 20:19 UTC by JonathanBanerjee

@lgiordani 

### What does this PR do?
Adds Leo's suggestions of deleting a volume of wordle_dbdata if it's already present.
Executes pg_isready to see if the PostgresDB is ready. 

How should this be manually tested?
By executing the bash script in the command line. 

Any background context you want to provide?
N/A

External context (Link to ticket etc)
N/A

2022-12-14 19:09 UTC, lgiordani requested changes

2022-12-14 19:09 UTC, lgiordani commented on create_db.sh
> +docker exec ${container_id} pg_isready
Have a look here https://www.postgresql.org/docs/current/app-pg-isready.html
The command `pg_isready` returns always, but you have to check the exit status to find out if it succeeded. I suggest you use a `while` loop with a `sleep` command in it.

2022-12-17 14:28 UTC, merged

2022-12-17 14:50 UTC, lgiordani commented
@JonathanBanerjee I suggested a change because your code in incorrect, why did you merge it?

2022-12-17 14:53 UTC, JonathanBanerjee commented
@lgiordani I wanted to add my progress so far, I have created a new branch to work on the suggested changes (working on them now). 
Question: Should the while loop be a part of the docker exec line, or should it be a line below in its own right?